name: "CI Tests"

on:
    pull_request:
    push:

jobs:
    tests:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.can-fail }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    # LTS with last stable PHP
                    - php: 8.3
                      symfony: 6.4.*
                      can-fail: false
                        # Stable Symfony branches
                    - php: 8.3
                      symfony: 7.0.*
                      can-fail: false
        
        name: "PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"
        
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Cache Composer packages"
              uses: "actions/cache@v4"
              with:
                  path: "~/.composer/cache"
                  key: "php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}"
                  restore-keys: "php-"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php }}"
                  tools: "composer:v2,flex"

            - name: "Install dependencies"
              run: "composer update ${{ matrix.composer-flags }} --prefer-dist"
              env:
                  SYMFONY_REQUIRE: "${{ matrix.symfony }}"

            - name: "Run PHPUnit Tests"
              run: "composer test"
